# import libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
from sqlalchemy import create_engine

In [2]:
#ignore all warnings
warnings.filterwarnings('ignore')

# Data Loading

In [3]:
Sales_df=pd.read_csv(r"E:\Samsung\fact_sales.csv")
Customer_df=pd.read_csv(r"E:\Samsung\dim_customer.csv")
Product_df=pd.read_csv(r"E:\Samsung\dim_product.csv")
Date_df=pd.read_csv(r"E:\Samsung\dim_date.csv")
Facility_df=pd.read_csv(r"E:\Samsung\dim_facility.csv")
Supplier_df=pd.read_csv(r"E:\Samsung\dim_supplier.csv")
Inventory_df=pd.read_csv(r"E:\Samsung\fact_inventory.csv")
Procurement_df=pd.read_csv(r"E:\Samsung\fact_procurement.csv")
Production_df=pd.read_csv(r"E:\Samsung\fact_production.csv")
Shipment_df=pd.read_csv(r"E:\Samsung\fact_shipment.csv")

# Exploratory Data Analysis (EDA)

#### Sales

In [4]:
Sales_df.head()

,sales_id,date_key,product_id,customer_id,quantity_sold,unit_price,discount_pct,discount_amount,gross_revenue,net_revenue,total_cost,profit,profit_margin_pct,order_number
0,1,226,15,5,36,429.99,0,0.00,15479.64,15479.64,10835.64,4644.00,30.00,ORD-202308-895667
1,2,164,14,3,5,1299.99,0,0.00,6499.95,6499.95,4224.95,2275.00,35.00,ORD-202306-325772
2,3,345,4,1,49,699.99,0,0.00,34299.51,34299.51,24009.51,10290.00,30.00,ORD-202312-476417
3,4,353,9,1,30,219.99,15,989.96,6599.70,5609.74,4619.70,990.04,17.65,ORD-202312-230889
4,5,388,3,5,19,849.99,25,4037.45,16149.81,12112.36,11304.81,807.55,6.67,ORD-202401-759176

In [5]:
Sales_df.duplicated().sum()

np.int64(0)

In [6]:
Sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sales_id           8500 non-null   int64
 1   date_key           8500 non-null   int64
 2   product_id         8500 non-null   int64
 3   customer_id        8500 non-null   int64
 4   quantity_sold      8500 non-null   int64
 5   unit_price         8500 non-null   float64
 6   discount_pct       8500 non-null   int64
 7   discount_amount    8500 non-null   float64
 8   gross_revenue      8500 non-null   float64
 9   net_revenue        8500 non-null   float64
 10  total_cost         8500 non-null   float64
 11  profit             8500 non-null   float64
 12  profit_margin_pct  8500 non-null   float64
 13  order_number       8500 non-null   object
dtypes: float64(7), int64(6), object(1)
memory usage: 929.8+ KB

## Customer

In [7]:
Customer_df.head()

,customer_id,customer_key,customer_name,country,channel_type,size,annual_volume_usd
0,1,CUST-US-AMZ-001,Amazon.com Inc.,USA,Online,Large,1200000000
1,2,CUST-US-BBY-001,Best Buy Co. Inc.,USA,Retailer,Large,850000000
2,3,CUST-EU-MMK-001,MediaMarkt Saturn,Germany,Retailer,Large,450000000
3,4,CUST-IN-FLP-001,Flipkart,India,Online,Large,420000000
4,5,CUST-KR-SSD-001,Samsung Direct Store,South Korea,Direct,Large,650000000

In [8]:
Customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5 non-null      int64
 1   customer_key       5 non-null      object
 2   customer_name      5 non-null      object
 3   country            5 non-null      object
 4   channel_type       5 non-null      object
 5   size               5 non-null      object
 6   annual_volume_usd  5 non-null      int64
dtypes: int64(2), object(5)
memory usage: 412.0+ bytes

## Product

In [9]:
Product_df.head()

,product_id,product_key,product_name,category,product_line,spec,color,unit_price,unit_cost,weight_kg,Img
0,1,SM-S928UZKAXAA,Galaxy S24 Ultra,Smartphone,Galaxy S,512GB,Phantom Black,1299.99,899.99,0.21,https://i.ibb.co/9Hv19S22/s24-Ultra.webp
1,2,SM-S928UZAAXAA,Galaxy S24 Ultra,Smartphone,Galaxy S,256GB,Titanium Gray,1199.99,839.99,0.15,https://i.ibb.co/9Hv19S22/s24-Ultra.webp
2,3,SM-S921ULVAXAA,Galaxy S24,Smartphone,Galaxy S,256GB,Cobalt Violet,849.99,594.99,0.18,https://i.ibb.co/gMJgXrhG/s24.webp
3,4,SM-S911UCEAXAA,Galaxy S23,Smartphone,Galaxy S,128GB,Cream,699.99,489.99,0.17,https://i.ibb.co/tPH2nTkP/s23.webp
4,5,SM-F946UZKAXAA,Galaxy Z Fold5,Smartphone,Galaxy Z,512GB,Phantom Black,1919.99,1343.99,0.22,https://i.ibb.co/tPnpz3yp/Folf5.webp

In [10]:
Product_df.duplicated().sum()

np.int64(0)

In [11]:
Product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    16 non-null     int64
 1   product_key   16 non-null     object
 2   product_name  16 non-null     object
 3   category      16 non-null     object
 4   product_line  16 non-null     object
 5   spec          16 non-null     object
 6   color         16 non-null     object
 7   unit_price    16 non-null     float64
 8   unit_cost     16 non-null     float64
 9   weight_kg     16 non-null     float64
 10  Img           16 non-null     object
dtypes: float64(3), int64(1), object(7)
memory usage: 1.5+ KB

## Date

In [12]:
Date_df.head()

,date_key,date,year,quarter,month,month_name,week,day,day_of_week,day_name,is_weekend
0,1,2023-01-01,2023,1,1,January,52,1,6,Sunday,1
1,2,2023-01-02,2023,1,1,January,1,2,0,Monday,0
2,3,2023-01-03,2023,1,1,January,1,3,1,Tuesday,0
3,4,2023-01-04,2023,1,1,January,1,4,2,Wednesday,0
4,5,2023-01-05,2023,1,1,January,1,5,3,Thursday,0

In [13]:
Date_df.duplicated().sum()

np.int64(0)

In [14]:
Date_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date_key     731 non-null    int64
 1   date         731 non-null    object
 2   year         731 non-null    int64
 3   quarter      731 non-null    int64
 4   month        731 non-null    int64
 5   month_name   731 non-null    object
 6   week         731 non-null    int64
 7   day          731 non-null    int64
 8   day_of_week  731 non-null    int64
 9   day_name     731 non-null    object
 10  is_weekend   731 non-null    int64
dtypes: int64(8), object(3)
memory usage: 62.9+ KB

## Facility

In [15]:
Facility_df.head()

,facility_id,facility_key,facility_name,country,city,facility_type,specialization,annual_capacity
0,1,FAC-KR-GUM-P1,Gumi Manufacturing 1,South Korea,Gumi,Manufacturing,Smartphone,850000
1,2,FAC-VN-TNG-P1,Thai Nguyen Plant,Vietnam,Thai Nguyen,Manufacturing,Mobile Assembly,1500000
2,3,FAC-KR-GUM-P3,Gumi Appliance Plant,South Korea,Gumi,Manufacturing,Appliances,320000
3,4,WH-US-NJ-DC1,New Jersey DC,USA,Cranbury,Warehouse,North America,500000
4,5,WH-EU-PL-DC1,Poland DC,Poland,Warsaw,Warehouse,Europe,520000

In [16]:
Facility_df.duplicated().sum()

np.int64(0)

In [17]:
Facility_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   facility_id      6 non-null      int64
 1   facility_key     6 non-null      object
 2   facility_name    6 non-null      object
 3   country          6 non-null      object
 4   city             6 non-null      object
 5   facility_type    6 non-null      object
 6   specialization   6 non-null      object
 7   annual_capacity  6 non-null      int64
dtypes: int64(2), object(6)
memory usage: 516.0+ bytes

## Supplier

In [18]:
Supplier_df.head()

,supplier_id,supplier_key,supplier_name,country,city,specialty,tier,avg_quality_score
0,1,SUP-KR-SEC-001,Samsung Electronics Co. Ltd,South Korea,Seoul,Integrated Components,Tier 1,98.5
1,2,SUP-KR-SKH-002,SK Hynix Inc.,South Korea,Icheon,DRAM & NAND Flash,Tier 1,97.8
2,3,SUP-TW-TSM-001,Taiwan Semiconductor Mfg,Taiwan,Hsinchu,Processors,Tier 1,99.2
3,4,SUP-JP-SON-001,Sony Semiconductor,Japan,Tokyo,Image Sensors,Tier 1,98.9
4,5,SUP-CN-BOE-001,BOE Technology,China,Beijing,Display Panels,Tier 1,96.5

In [19]:
Supplier_df.duplicated().sum()

np.int64(0)

In [20]:
Supplier_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   supplier_id        7 non-null      int64
 1   supplier_key       7 non-null      object
 2   supplier_name      7 non-null      object
 3   country            7 non-null      object
 4   city               7 non-null      object
 5   specialty          7 non-null      object
 6   tier               7 non-null      object
 7   avg_quality_score  7 non-null      float64
dtypes: float64(1), int64(1), object(6)
memory usage: 580.0+ bytes

## Inventory

In [21]:
Inventory_df.head()

,inventory_id,date_key,product_id,facility_id,stock_level,safety_stock_level,reorder_point
0,1,31,1,4,138,53,88
1,2,31,1,5,121,53,88
2,3,31,1,6,127,53,88
3,4,31,2,4,232,113,145
4,5,31,2,5,266,113,145

In [22]:
Inventory_df.duplicated().sum()

np.int64(0)

In [23]:
Inventory_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1152 entries, 0 to 1151
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inventory_id        1152 non-null   int64
 1   date_key            1152 non-null   int64
 2   product_id          1152 non-null   int64
 3   facility_id         1152 non-null   int64
 4   stock_level         1152 non-null   int64
 5   safety_stock_level  1152 non-null   int64
 6   reorder_point       1152 non-null   int64
dtypes: int64(7)
memory usage: 63.1 KB

## Procurement

In [24]:
Procurement_df.head()

,procurement_id,order_date_key,product_id,supplier_id,order_quantity,unit_cost,total_cost,lead_time_days,delivery_date_key,quality_score,po_number
0,1,646,15,6,53,199.23,10559.19,12,658,94.9,PO-2024-294458
1,2,651,7,1,50,636.67,31833.50,17,668,96.9,PO-2024-189045
2,3,632,16,3,121,120.73,14608.33,13,645,98.0,PO-2024-394238
3,4,62,12,1,50,285.66,14283.00,8,70,98.4,PO-2023-777368
4,5,315,13,4,50,1587.75,79387.50,16,331,98.6,PO-2023-137156

In [25]:
Procurement_df.duplicated().sum()

np.int64(0)

In [26]:
Procurement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   procurement_id     2200 non-null   int64
 1   order_date_key     2200 non-null   int64
 2   product_id         2200 non-null   int64
 3   supplier_id        2200 non-null   int64
 4   order_quantity     2200 non-null   int64
 5   unit_cost          2200 non-null   float64
 6   total_cost         2200 non-null   float64
 7   lead_time_days     2200 non-null   int64
 8   delivery_date_key  2200 non-null   int64
 9   quality_score      2200 non-null   float64
 10  po_number          2200 non-null   object
dtypes: float64(3), int64(7), object(1)
memory usage: 189.2+ KB

## Production

In [27]:
Production_df.head()

,production_id,date_key,product_id,facility_id,quantity_produced,defective_units,defect_rate_pct,batch_number
0,1,376,11,3,60,0,1.13,PROD-2024017422
1,2,78,13,3,81,0,0.74,PROD-2023039595
2,3,441,4,1,1997,23,1.20,PROD-2024033020
3,4,161,1,3,1703,12,0.74,PROD-2023068538
4,5,529,13,2,40,0,0.33,PROD-2024062367

In [28]:
Production_df.duplicated().sum()

np.int64(0)

In [29]:
Production_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   production_id      4500 non-null   int64
 1   date_key           4500 non-null   int64
 2   product_id         4500 non-null   int64
 3   facility_id        4500 non-null   int64
 4   quantity_produced  4500 non-null   int64
 5   defective_units    4500 non-null   int64
 6   defect_rate_pct    4500 non-null   float64
 7   batch_number       4500 non-null   object
dtypes: float64(1), int64(6), object(1)
memory usage: 281.4+ KB

## Shipment

In [30]:
Shipment_df.head()

,shipment_id,ship_date_key,delivery_date_key,product_id,facility_id,customer_id,quantity,carrier,status,shipping_cost,total_weight_kg,tracking_number,delay_reason
0,1,648,658,28,15,7,23,Maersk Line,Delivered,4086.00,1372.41,MAE9551166427,NaN
1,2,489,516,28,11,5,81,DB Schenker,In Transit,5062.52,4833.27,DB 1542288166,NaN
2,3,357,373,28,15,16,39,XPO Logistics,Delayed,4541.01,2327.13,XPO1070033276,Security Check
3,4,424,435,26,11,17,64,DHL Express,Delivered,5270.26,1606.40,DHL7255101456,NaN
4,5,515,528,17,10,11,281,FedEx International,Delivered,674.33,143.31,FED1783808225,NaN

In [31]:
Shipment_df.duplicated().sum()

np.int64(0)

In [32]:
Shipment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shipment_id        7500 non-null   int64
 1   ship_date_key      7500 non-null   int64
 2   delivery_date_key  7500 non-null   int64
 3   product_id         7500 non-null   int64
 4   facility_id        7500 non-null   int64
 5   customer_id        7500 non-null   int64
 6   quantity           7500 non-null   int64
 7   carrier            7500 non-null   object
 8   status             7500 non-null   object
 9   shipping_cost      7500 non-null   float64
 10  total_weight_kg    7500 non-null   float64
 11  tracking_number    7500 non-null   object
 12  delay_reason       573 non-null    object
dtypes: float64(2), int64(7), object(4)
memory usage: 761.8+ KB

In [33]:
Shipment_df.groupby('delay_reason',dropna=False).size()

delay_reason
Address Exception        59
Carrier Capacity         90
Customs Clearance        71
Documentation Issue      78
Mechanical Failure       67
Port Congestion          73
Security Check           67
Weather Disruption       68
NaN                    6927
dtype: int64

##### *******************************************************************************************************************************

# Data Cleaning

#### All Data Tables Cleaned Successfully Except for Shipment Table

#### Shipment

##### Handling Missing Values in Dataset

In [34]:
Shipment_df['delay_reason']=Shipment_df['delay_reason'].fillna('On Time')
# cheack
Shipment_df['delay_reason'].head()

0           On Time
1           On Time
2    Security Check
3           On Time
4           On Time
Name: delay_reason, dtype: object

# Feature Engineering

#### Shipment

In [35]:
Shipment_df['Shipment_Status']=Shipment_df['delay_reason'].apply(
    lambda x : "On Time" if x == "On Time"
    else "Delayed"
)
# cheack
Shipment_df['Shipment_Status'].value_counts()

Shipment_Status
On Time    6927
Delayed     573
Name: count, dtype: int64

### Stock Level Analysis Using Safety Stock Thresholds

In [43]:
Warning_level= Inventory_df['safety_stock_level'] *1.1

Inventory_df['Safety_Status'] = np.select([
    Inventory_df['stock_level'] < Inventory_df['safety_stock_level'],
    Inventory_df['stock_level'] <= Warning_level,
    Inventory_df['stock_level'] > Warning_level],
                                          
    ['Critical','Warning','Safe'],
     default='Check Data')
# Cheack
Inventory_df.head()

,inventory_id,date_key,product_id,facility_id,stock_level,safety_stock_level,reorder_point,Safety_Status,Reorder_Status
0,1,31,1,4,138,53,88,Safe,Sufficient Stock
1,2,31,1,5,121,53,88,Safe,Sufficient Stock
2,3,31,1,6,127,53,88,Safe,Sufficient Stock
3,4,31,2,4,232,113,145,Safe,Sufficient Stock
4,5,31,2,5,266,113,145,Safe,Sufficient Stock

### Inventory Replenishment Status Using Reorder Point

In [38]:
diff=Inventory_df['stock_level'] - Inventory_df['reorder_point']

Inventory_df['Reorder_Status']=np.select(
    [diff>0,diff==0,diff<0],
    ['Sufficient Stock','Reorder Point Reached','Overdue / Order Now'],
    default='Check Data'
)
# Cheack
Inventory_df.head()

,inventory_id,date_key,product_id,facility_id,stock_level,safety_stock_level,reorder_point,Safety_Status,Reorder_Status
0,1,31,1,4,138,53,88,Safe,Sufficient Stock
1,2,31,1,5,121,53,88,Safe,Sufficient Stock
2,3,31,1,6,127,53,88,Safe,Sufficient Stock
3,4,31,2,4,232,113,145,Safe,Sufficient Stock
4,5,31,2,5,266,113,145,Safe,Sufficient Stock

#### ETL Pipeline Execution Completed

In [48]:
server = 'samyasar'
database = 'Samsung'
username = 'sa'
password = '123'

engine = create_engine(
    f"mssql+pyodbc://{username}:{password}@{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

tables = {
    "dim_customer": Customer_df,
    "dim_date": Date_df,
    "dim_facility": Facility_df,
    "dim_product": Product_df,
    "dim_supplier": Supplier_df,

    "fact_inventory": Inventory_df,
    "fact_procurement": Procurement_df,
    "fact_production": Production_df,
    "fact_sales": Sales_df,
    "fact_shipment": Shipment_df
}

for table_name, df in tables.items():
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False
    )
print("***********************************************************")    
print("****************** Data upload complete *******************")
print("***********************************************************")

***********************************************************
****************** Data upload complete *******************
***********************************************************